*msi download*
http://dev.mysql.com/downloads/installer/

*zip download*
http://dev.mysql.com/downloads/mysql/

*portable version*
http://stackoverflow.com/questions/1851174/mysql-portable-version

*Installing MySQL on Microsoft Windows Using a noinstall Zip Archive*
http://dev.mysql.com/doc/refman/5.1/en/windows-install-archive.html

--------------------------------------------------------------
1-download zip distribution
2-unzip bin\
	mysql.exe - cmd administration
	mysqladmin.exe - start/stop server
	mysqld.exe - the server it self
	mysqldump.exe - used for backups
  unzip share\*.*
  unzip data\*.* (exclude ib_logfile*.*)
3-setup my.ini
--------------------------------------------------------------

//create new user + dbase
mysql -u root -p
create database testDB2;
create user pp2;
grant all on testDB2.* to 'pp2'@'localhost' identified by 'pp';
//enable to manipulate users - grant all on *.* to 'pp2'@'localhost' identified by 'pp';

FLUSH PRIVILEGES;
EXIT
echo Exit from MYSQL...

//change password
//http://www.cyberciti.biz/faq/mysql-change-root-password/


//to start MYSQL use :
mysqld.exe

//to stop MYSQL use :
mysqladmin.exe -u root -p shutdown
pause

//***********MISC [start]
http://stackoverflow.com/questions/5774251/create-mysql-db-from-command-line
https://www.digitalocean.com/community/articles/how-to-create-a-new-user-and-grant-permissions-in-mysql
http://www.lanexa.net/2011/08/create-a-mysql-database-username-password-and-permissions-from-the-command-line/
http://www.cyberciti.biz/faq/mysql-user-creation/
http://www.andrehonsberg.com/article/add-new-user-mysql-database-command-line
utf8 - http://stackoverflow.com/questions/3513773/change-mysql-default-character-set-to-utf8-in-my-cnf
create my.ini - https://tools.percona.com/
shutdown proper - mysqladmin.exe -u root -p shutdown

restrict to local only - add "bind-address = 127.0.0.1" to the "[mysqld]" section 
http://stackoverflow.com/questions/13208614/restricting-mysql-connections-from-localhost-to-improve-security

execute via command line - mysql -h host -u user -p -e 'SHOW TABLES FROM test'
//***********MISC [end]

//my.ini with UTF8
# For advice on how to change settings please see
# http://dev.mysql.com/doc/refman/5.6/en/server-configuration-defaults.html
# *** DO NOT EDIT THIS FILE. It's a template which will be copied to the
# *** default location during install, and will be replaced if you
# *** upgrade to a newer version of MySQL.
[mysqld]
explicit_defaults_for_timestamp = TRUE

init_connect='SET collation_connection = utf8_unicode_ci' 
init_connect='SET NAMES utf8' 
character-set-server=utf8 
collation-server=utf8_unicode_ci 
skip-character-set-client-handshake

# Remove leading # and set to the amount of RAM for the most important data
# cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
# innodb_buffer_pool_size = 128M

# Remove leading # to turn on a very important data integrity option: logging
# changes to the binary log between backups.
# log_bin

# These are commonly set, remove the # and set as required.
basedir = ".."
datadir = "../data"
port = 3306
server_id = myMYSQL


# Remove leading # to set options mainly useful for reporting servers.
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
# join_buffer_size = 128M
# sort_buffer_size = 2M
# read_rnd_buffer_size = 2M 

sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES 
