 --disable FK constraints
ALTER TABLE Orders NOCHECK CONSTRAINT ALL
ALTER TABLE OrdersDetails NOCHECK CONSTRAINT ALL
ALTER TABLE peltemplate NOCHECK CONSTRAINT ALL
ALTER TABLE pelates NOCHECK CONSTRAINT ALL
ALTER TABLE axiografa NOCHECK CONSTRAINT ALL
ALTER TABLE SNDetails NOCHECK CONSTRAINT ALL
ALTER TABLE Contactsipok NOCHECK CONSTRAINT ALL

--delete rows
DELETE FROM orders
DELETE FROM OrdersDetails
DELETE FROM peltemplate
DELETE FROM pelates
DELETE FROM sn
DELETE FROM TimolProducts
DELETE FROM products
DELETE FROM Timokatalogos
DELETE FROM TimolPrices
DELETE FROM TimolProducts
DELETE FROM Contactsipok

--enable FK constraints
ALTER TABLE orders CHECK CONSTRAINT ALL
ALTER TABLE OrdersDetails CHECK CONSTRAINT ALL
ALTER TABLE peltemplate CHECK CONSTRAINT ALL
ALTER TABLE pelates CHECK CONSTRAINT ALL
ALTER TABLE axiografa CHECK CONSTRAINT ALL
ALTER TABLE SNDetails CHECK CONSTRAINT ALL
ALTER TABLE Contactsipok CHECK CONSTRAINT ALL

