Private Function Crypt(a$) As String
Dim res1 As String
Dim res2 As String
Dim res As String
Dim i As Integer

For i = 1 To Len(a)

res1 = LCase(Mid(a, i, 1))
    Select Case res1
        Case "1"
            res2 = "*"
        Case "2"
            res2 = "-"
        Case "3"
            res2 = "l"
        Case "4"
            res2 = "j"
        Case "5"
            res2 = "9"
        Case "6"
            res2 = "i"
        Case "7"
            res2 = "}"
        Case "8"
            res2 = "z"
        Case "9"
            res2 = "4"
        Case "0"
            res2 = "+"
        Case "a"
            res2 = "~"
        Case "b"
            res2 = "{"
        Case "c"
            res2 = ":"
        Case "d"
            res2 = "/"
        Case "e"
            res2 = "7"
        Case "f"
            res2 = "@"
        Case "g"
            res2 = "_"
        Case "h"
            res2 = "h"
        Case "i"
            res2 = "p"
        Case "j"
            res2 = "©"
        Case "k"
            res2 = "\"
        Case "l"
            res2 = "w"
        Case "m"
            res2 = "`"
        Case "n"
            res2 = "^"
        Case "o"
            res2 = "$"
        Case "p"
            res2 = ">"
        Case "q"
            res2 = "&"
        Case "r"
            res2 = "."
        Case "s"
            res2 = "#"
        Case "t"
            res2 = "1"
        Case "u"
            res2 = "!"
        Case "v"
            res2 = "<"
        Case "w"
            res2 = "v"
        Case "x"
            res2 = "t"
        Case "y"
            res2 = "?"
        Case "z"
            res2 = "["
        Case " "
            res2 = "b"
        Case "."
                res2 = "]"
        Case ":"
                res2 = "2"
        Case "/"
                res2 = "3"
        Case "?"
                res2 = "5"
        Case "="
                res2 = "6"
        Case "|"
                res2 = "8"
        Case "*"
                res2 = "0"
        Case "-"
                res2 = "g"
        Case "_"
                res2 = "o"
        Case Else
                MsgBox "Crypt :: [" & res1 & "] is NO supported :((" & vbCrLf & vbCrLf & "plz.. write down this char and inform veteran for this" & vbCrLf & vbCrLf & "The program now exit..." & vbCrLf & vbCrLf & "Donot try to re-import... meet veteran to fix the problem!", vbInformation, apTitle
                End
    End Select
    
    res = res & res2
Next i

Crypt = res
End Function



Private Function UnCrypt(a$) As String
Dim res1 As String
Dim res2 As String
Dim res As String
Dim i As Integer

For i = 1 To Len(a)

    res1 = LCase(Mid(a, i, 1))
    
    Select Case res1
    Case "*"
        res2 = "1"
    Case "-"
        res2 = "2"
    Case "l"
        res2 = "3"
    Case "j"
        res2 = "4"
    Case "9"
        res2 = "5"
    Case "i"
        res2 = "6"
    Case "}"
        res2 = "7"
    Case "z"
        res2 = "8"
    Case "4"
        res2 = "9"
    Case "+"
        res2 = "0"
    Case "~"
        res2 = "a"
    Case "{"
        res2 = "b"
    Case ":"
        res2 = "c"
    Case "/"
        res2 = "d"
    Case "7"
        res2 = "e"
    Case "@"
        res2 = "f"
    Case "_"
        res2 = "g"
    Case "h"
        res2 = "h"
    Case "p"
        res2 = "i"
    Case "©"
        res2 = "j"
    Case "\"
        res2 = "k"
    Case "w"
        res2 = "l"
    Case "`"
        res2 = "m"
    Case "^"
        res2 = "n"
    Case "$"
        res2 = "o"
    Case ">"
        res2 = "p"
    Case "&"
        res2 = "q"
    Case "."
        res2 = "r"
    Case "#"
        res2 = "s"
    Case "1"
        res2 = "t"
    Case "!"
        res2 = "u"
    Case "<"
        res2 = "v"
    Case "v"
        res2 = "w"
    Case "t"
        res2 = "x"
    Case "?"
        res2 = "y"
    Case "["
        res2 = "z"
    Case "b"
        res2 = " "
    Case "]"
        res2 = "."
    Case "2"
        res2 = ":"
    Case "3"
        res2 = "/"
    Case "5"
        res2 = "?"
    Case "6"
        res2 = "="
    Case "8"
        res2 = "|"
    Case "0"
        res2 = "*"
    Case "g"
            res2 = "-"
    Case "o"
            res2 = "_"
End Select

res = res & res2

Next i

UnCrypt = res

End Function